### ISSUE TITLE
Error "previousFailure cannot be resolved to a variable"

### ISSUE THREAD

**Issue by asheiduk** [LorenzoBettini/xsemantics#46]
Hello,

I'm testing Xsemantics 1.7 and the following Java error crossed my way:

    previousFailure cannot be resolved to a variable

The system itself does use this variable: 

	import org.eclipse.emf.ecore.EObject
	
	system Foo 
	
	judgments {
		type |- EObject it : output String
	}
	
	axiom typeFoo
		G |- EObject it : "Foo"
		
	checkrule checkEObject for EObject it from {
		if( eClass == null ){
			empty |- it : var String result
			or true
		}
		else {
			var String result    // This must be on a separate line to reproduce the error!
			empty |- eClass : result
			or true
		}
	}

The Java-code has this structure:

    if(...){
         RuleFailedException previousFailure = null;
         ...
    } else {
         try { ... }
         catch(Exception e_1){
            previousFailure = extractRuleFailedException(e_1);
        }
    }

**Comment by LorenzoBettini** [comment]
version 1.7.1 has been released with this fix
