### ISSUE TITLE
Access Restriction on Project

### ISSUE THREAD

**Issue by shunghsiyu** [LorenzoBettini/xsemantics#47]
Hi,
  When writing JUnit tests in a separate project ("tests" project created by Xtext) rather than in the main Xtext project. Eclipse complains about access restriction imposed on the main project when I try to access the type system class created by Xsemantics.
  I was able to resolve the problem by following [this](http://help.eclipse.org/indigo/index.jsp?topic=/org.eclipse.pde.doc.user/guide/tools/editors/manifest_editor/access_rules.htm) guide to add the "typing" project to the list of exported packages.
 
I wonder if this can be done by Xsemantics automatically in the future

**Comment by LorenzoBettini** [comment]
I have added a section in the documentation about the generated Java packages.

**Comment by shunghsiyu** [comment]
Thank you!
