### ISSUE TITLE
Errors in expression example project

### ISSUE THREAD

**Issue by lwrage** [LorenzoBettini/xsemantics#63]
When trying the example expression language I ran into the following problems with the GenerateXsemanticsArtifacts workflow: 
- There's a missing dependency on org.eclipse.core.runtime
- I get a validation error.
```
5749 [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow GenerateXsemanticsArtifacts: Validation problems: 
12 errors:
	expressions-first.xsemantics - /home/lw/projects/osate/ws1/it.xsemantics.example.expressions/src/it/xsemantics/example/expressions/typing/expressions-first.xsemantics
		28: The type ExpressionsSemantics is already defined in expressions-first.xsemantics.
		28: The type ExpressionsSemanticsValidator is already defined in expressions-first.xsemantics.
	expressions-cached.xsemantics - /home/lw/projects/osate/ws1/it.xsemantics.example.expressions/src/it/xsemantics/example/expressions/typing/expressions-cached.xsemantics
		9: The type CachedExpressionsSemantics is already defined in expressions-cached.xsemantics.
		9: The type CachedExpressionsSemanticsValidator is already defined in expressions-cached.xsemantics.
...
```
The underlying problem seems to be that the URI filter in the Reader workflow component is ineffective. The generation step works fine after I manually delete all xsemantics files from the `bin` directory.

Eclipse Mars.1, Xtext 2.8.4, Xsemantics 1.8.1

**Comment by LorenzoBettini** [comment]
Hi
That specific mwe2 file is not intended to be used by the users, but only during the development, to compile Xsemantics files without running another Eclipse instance. However, as you said, those should be fixed accordingly. I think the appropriate fix is to remove the option to use the classpath. I'll look into that and I keep this issue open until I fixed that.
Thanks

**Comment by LorenzoBettini** [comment]
I think it's better to completely remove those GenerateXsemanticsArtifacts.mwe2 from examples: they used to be useful at development time, but now are completely useless and do not work anyway (they would not even pick up the right Java compilation version).
