### ISSUE TITLE
provide a xtext 2.10.x version of Xsemantics

### ISSUE THREAD

**Issue by cdietrich** [LorenzoBettini/xsemantics#69]

**Comment by LorenzoBettini** [comment]
I'll work on that in the next few days

**Comment by LorenzoBettini** [comment]
Xsemantics 1.10 snapshots, built with Xtext 2.10 nightly are available: 

https://dl.bintray.com/lorenzobettini/xsemantics/snapshots/updates/

(maven snapshots are also available from maven central)

Official release 1.10 will be available when Xtext 2.10 will be released.
