### ISSUE TITLE
release Xsemantics for Xtext 2.11

### ISSUE THREAD

**Issue by meysholdt** [LorenzoBettini/xsemantics#76]
Currently, Xsemantics can't be installed together with Xtext 2.11 because Xsemantics has an upper version constraint that excludes Xtext 2.11.

Example: https://github.com/LorenzoBettini/xsemantics/blob/master/plugins/it.xsemantics.dsl/META-INF/MANIFEST.MF#L9

**Comment by LorenzoBettini** [comment]
I'll work on that tomorrow, but I'll release a snapshot version, and release the final version when xtext 2.11 is officially release

**Comment by LorenzoBettini** [comment]
Also regenerate code of the examples

**Comment by LorenzoBettini** [comment]
@meysholdt sorry for the delay. Maven snapshots for 1.11 are on Maven Central and the p2 repo is https://dl.bintray.com/lorenzobettini/xsemantics/snapshots/updates/1.11/

**Comment by LorenzoBettini** [comment]
In a few minutes, version 1.11.0 for Xtext 2.11.0 will be available
