### ISSUE TITLE
Generate copyright header

### ISSUE THREAD

**Issue by JensN4** [LorenzoBettini/xsemantics#86]
We need a copyright header in the generated files.

I suggest to add a new optional attribute to the typesystem "copyright". E.g., 

```
system it.xsemantics.test.fj.first.FjFirstTypeSystem

copyright "(C) This is a test\ncopyright header."

validatorExtends AbstractFJJavaValidator
```

**Comment by LorenzoBettini** [comment]
fixed by https://github.com/LorenzoBettini/xsemantics/pull/87

**Comment by LorenzoBettini** [comment]
Version 1.11.2 has been released with this feature. Thank you for the contribution :)
