### ISSUE TITLE
Prepare the Xsemantics repository w.r.t. copyright headers, file types, white spaces, etc.

### ISSUE THREAD

**Issue by mmews-n4** [LorenzoBettini/xsemantics#94]
Some changes are still necessary for the migration of Xsemantics:
* some files still need a copyright header to be added or slightly adjusted to the standard form
* some test data files and README/NOTE/etc. files should copyright headers
* about.html should be added
* Bundle/Vendor ID and project files should be adjusted
* ...

**Comment by LorenzoBettini** [comment]
Closed by https://github.com/LorenzoBettini/xsemantics/pull/95
